/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupermarketsRouteImport } from './routes/supermarkets'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HomeBusinessesRouteImport } from './routes/home-businesses'
import { Route as GoRouteImport } from './routes/go'
import { Route as FeaturedRouteImport } from './routes/featured'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DessertsRouteImport } from './routes/desserts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CafesRouteImport } from './routes/cafes'
import { Route as BakeriesRouteImport } from './routes/bakeries'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SServiceRouteImport } from './routes/s.$service'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as BusinessIdRouteImport } from './routes/business.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicSheetSyncRouteImport } from './routes/api/public/sheet-sync'
import { Route as ApiPublicEventRouteImport } from './routes/api/public/event'
import { Route as ApiPublicCoverRouteImport } from './routes/api/public/cover'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAppearanceRouteImport } from './routes/_authenticated/admin.appearance'
import { Route as AuthenticatedAdminBusinessesIndexRouteImport } from './routes/_authenticated/admin.businesses.index'
import { Route as ApiPublicCoverPathRouteImport } from './routes/api/public/cover.$path'
import { Route as AuthenticatedAdminBusinessesIdRouteImport } from './routes/_authenticated/admin.businesses.$id'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupermarketsRoute = SupermarketsRouteImport.update({
  id: '/supermarkets',
  path: '/supermarkets',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBusinessesRoute = HomeBusinessesRouteImport.update({
  id: '/home-businesses',
  path: '/home-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedRoute = FeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DessertsRoute = DessertsRouteImport.update({
  id: '/desserts',
  path: '/desserts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CafesRoute = CafesRouteImport.update({
  id: '/cafes',
  path: '/cafes',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeriesRoute = BakeriesRouteImport.update({
  id: '/bakeries',
  path: '/bakeries',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SServiceRoute = SServiceRouteImport.update({
  id: '/s/$service',
  path: '/s/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicSheetSyncRoute = ApiPublicSheetSyncRouteImport.update({
  id: '/api/public/sheet-sync',
  path: '/api/public/sheet-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventRoute = ApiPublicEventRouteImport.update({
  id: '/api/public/event',
  path: '/api/public/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCoverRoute = ApiPublicCoverRouteImport.update({
  id: '/api/public/cover',
  path: '/api/public/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAppearanceRoute =
  AuthenticatedAdminAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBusinessesIndexRoute =
  AuthenticatedAdminBusinessesIndexRouteImport.update({
    id: '/businesses/',
    path: '/businesses/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCoverPathRoute = ApiPublicCoverPathRouteImport.update({
  id: '/$path',
  path: '/$path',
  getParentRoute: () => ApiPublicCoverRoute,
} as any)
const AuthenticatedAdminBusinessesIdRoute =
  AuthenticatedAdminBusinessesIdRouteImport.update({
    id: '/businesses/$id',
    path: '/businesses/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bakeries': typeof BakeriesRoute
  '/cafes': typeof CafesRoute
  '/contact': typeof ContactRoute
  '/desserts': typeof DessertsRoute
  '/favorites': typeof FavoritesRoute
  '/featured': typeof FeaturedRoute
  '/go': typeof GoRoute
  '/home-businesses': typeof HomeBusinessesRoute
  '/mcp': typeof McpRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supermarkets': typeof SupermarketsRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/business/$id': typeof BusinessIdRoute
  '/c/$slug': typeof CSlugRoute
  '/s/$service': typeof SServiceRoute
  '/admin/appearance': typeof AuthenticatedAdminAppearanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/api/public/cover': typeof ApiPublicCoverRouteWithChildren
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/sheet-sync': typeof ApiPublicSheetSyncRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/businesses/$id': typeof AuthenticatedAdminBusinessesIdRoute
  '/api/public/cover/$path': typeof ApiPublicCoverPathRoute
  '/admin/businesses/': typeof AuthenticatedAdminBusinessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bakeries': typeof BakeriesRoute
  '/cafes': typeof CafesRoute
  '/contact': typeof ContactRoute
  '/desserts': typeof DessertsRoute
  '/favorites': typeof FavoritesRoute
  '/featured': typeof FeaturedRoute
  '/go': typeof GoRoute
  '/home-businesses': typeof HomeBusinessesRoute
  '/mcp': typeof McpRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supermarkets': typeof SupermarketsRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/business/$id': typeof BusinessIdRoute
  '/c/$slug': typeof CSlugRoute
  '/s/$service': typeof SServiceRoute
  '/admin/appearance': typeof AuthenticatedAdminAppearanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/api/public/cover': typeof ApiPublicCoverRouteWithChildren
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/sheet-sync': typeof ApiPublicSheetSyncRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/businesses/$id': typeof AuthenticatedAdminBusinessesIdRoute
  '/api/public/cover/$path': typeof ApiPublicCoverPathRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bakeries': typeof BakeriesRoute
  '/cafes': typeof CafesRoute
  '/contact': typeof ContactRoute
  '/desserts': typeof DessertsRoute
  '/favorites': typeof FavoritesRoute
  '/featured': typeof FeaturedRoute
  '/go': typeof GoRoute
  '/home-businesses': typeof HomeBusinessesRoute
  '/mcp': typeof McpRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supermarkets': typeof SupermarketsRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/business/$id': typeof BusinessIdRoute
  '/c/$slug': typeof CSlugRoute
  '/s/$service': typeof SServiceRoute
  '/_authenticated/admin/appearance': typeof AuthenticatedAdminAppearanceRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/api/public/cover': typeof ApiPublicCoverRouteWithChildren
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/sheet-sync': typeof ApiPublicSheetSyncRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/businesses/$id': typeof AuthenticatedAdminBusinessesIdRoute
  '/api/public/cover/$path': typeof ApiPublicCoverPathRoute
  '/_authenticated/admin/businesses/': typeof AuthenticatedAdminBusinessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bakeries'
    | '/cafes'
    | '/contact'
    | '/desserts'
    | '/favorites'
    | '/featured'
    | '/go'
    | '/home-businesses'
    | '/mcp'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/restaurants'
    | '/search'
    | '/sitemap.xml'
    | '/supermarkets'
    | '/terms'
    | '/waitlist'
    | '/admin'
    | '/business/$id'
    | '/c/$slug'
    | '/s/$service'
    | '/admin/appearance'
    | '/admin/audit'
    | '/admin/import'
    | '/admin/leads'
    | '/admin/messages'
    | '/api/public/cover'
    | '/api/public/event'
    | '/api/public/sheet-sync'
    | '/admin/'
    | '/admin/businesses/$id'
    | '/api/public/cover/$path'
    | '/admin/businesses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bakeries'
    | '/cafes'
    | '/contact'
    | '/desserts'
    | '/favorites'
    | '/featured'
    | '/go'
    | '/home-businesses'
    | '/mcp'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/restaurants'
    | '/search'
    | '/sitemap.xml'
    | '/supermarkets'
    | '/terms'
    | '/waitlist'
    | '/business/$id'
    | '/c/$slug'
    | '/s/$service'
    | '/admin/appearance'
    | '/admin/audit'
    | '/admin/import'
    | '/admin/leads'
    | '/admin/messages'
    | '/api/public/cover'
    | '/api/public/event'
    | '/api/public/sheet-sync'
    | '/admin'
    | '/admin/businesses/$id'
    | '/api/public/cover/$path'
    | '/admin/businesses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/bakeries'
    | '/cafes'
    | '/contact'
    | '/desserts'
    | '/favorites'
    | '/featured'
    | '/go'
    | '/home-businesses'
    | '/mcp'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/restaurants'
    | '/search'
    | '/sitemap.xml'
    | '/supermarkets'
    | '/terms'
    | '/waitlist'
    | '/_authenticated/admin'
    | '/business/$id'
    | '/c/$slug'
    | '/s/$service'
    | '/_authenticated/admin/appearance'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/messages'
    | '/api/public/cover'
    | '/api/public/event'
    | '/api/public/sheet-sync'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/businesses/$id'
    | '/api/public/cover/$path'
    | '/_authenticated/admin/businesses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BakeriesRoute: typeof BakeriesRoute
  CafesRoute: typeof CafesRoute
  ContactRoute: typeof ContactRoute
  DessertsRoute: typeof DessertsRoute
  FavoritesRoute: typeof FavoritesRoute
  FeaturedRoute: typeof FeaturedRoute
  GoRoute: typeof GoRoute
  HomeBusinessesRoute: typeof HomeBusinessesRoute
  McpRoute: typeof McpRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupermarketsRoute: typeof SupermarketsRoute
  TermsRoute: typeof TermsRoute
  WaitlistRoute: typeof WaitlistRoute
  BusinessIdRoute: typeof BusinessIdRoute
  CSlugRoute: typeof CSlugRoute
  SServiceRoute: typeof SServiceRoute
  ApiPublicCoverRoute: typeof ApiPublicCoverRouteWithChildren
  ApiPublicEventRoute: typeof ApiPublicEventRoute
  ApiPublicSheetSyncRoute: typeof ApiPublicSheetSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supermarkets': {
      id: '/supermarkets'
      path: '/supermarkets'
      fullPath: '/supermarkets'
      preLoaderRoute: typeof SupermarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-businesses': {
      id: '/home-businesses'
      path: '/home-businesses'
      fullPath: '/home-businesses'
      preLoaderRoute: typeof HomeBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured': {
      id: '/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof FeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desserts': {
      id: '/desserts'
      path: '/desserts'
      fullPath: '/desserts'
      preLoaderRoute: typeof DessertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafes': {
      id: '/cafes'
      path: '/cafes'
      fullPath: '/cafes'
      preLoaderRoute: typeof CafesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakeries': {
      id: '/bakeries'
      path: '/bakeries'
      fullPath: '/bakeries'
      preLoaderRoute: typeof BakeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$service': {
      id: '/s/$service'
      path: '/s/$service'
      fullPath: '/s/$service'
      preLoaderRoute: typeof SServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/sheet-sync': {
      id: '/api/public/sheet-sync'
      path: '/api/public/sheet-sync'
      fullPath: '/api/public/sheet-sync'
      preLoaderRoute: typeof ApiPublicSheetSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/event': {
      id: '/api/public/event'
      path: '/api/public/event'
      fullPath: '/api/public/event'
      preLoaderRoute: typeof ApiPublicEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cover': {
      id: '/api/public/cover'
      path: '/api/public/cover'
      fullPath: '/api/public/cover'
      preLoaderRoute: typeof ApiPublicCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appearance': {
      id: '/_authenticated/admin/appearance'
      path: '/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AuthenticatedAdminAppearanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/businesses/': {
      id: '/_authenticated/admin/businesses/'
      path: '/businesses'
      fullPath: '/admin/businesses/'
      preLoaderRoute: typeof AuthenticatedAdminBusinessesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cover/$path': {
      id: '/api/public/cover/$path'
      path: '/$path'
      fullPath: '/api/public/cover/$path'
      preLoaderRoute: typeof ApiPublicCoverPathRouteImport
      parentRoute: typeof ApiPublicCoverRoute
    }
    '/_authenticated/admin/businesses/$id': {
      id: '/_authenticated/admin/businesses/$id'
      path: '/businesses/$id'
      fullPath: '/admin/businesses/$id'
      preLoaderRoute: typeof AuthenticatedAdminBusinessesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAppearanceRoute: typeof AuthenticatedAdminAppearanceRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBusinessesIdRoute: typeof AuthenticatedAdminBusinessesIdRoute
  AuthenticatedAdminBusinessesIndexRoute: typeof AuthenticatedAdminBusinessesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAppearanceRoute: AuthenticatedAdminAppearanceRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBusinessesIdRoute: AuthenticatedAdminBusinessesIdRoute,
  AuthenticatedAdminBusinessesIndexRoute:
    AuthenticatedAdminBusinessesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicCoverRouteChildren {
  ApiPublicCoverPathRoute: typeof ApiPublicCoverPathRoute
}

const ApiPublicCoverRouteChildren: ApiPublicCoverRouteChildren = {
  ApiPublicCoverPathRoute: ApiPublicCoverPathRoute,
}

const ApiPublicCoverRouteWithChildren = ApiPublicCoverRoute._addFileChildren(
  ApiPublicCoverRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BakeriesRoute: BakeriesRoute,
  CafesRoute: CafesRoute,
  ContactRoute: ContactRoute,
  DessertsRoute: DessertsRoute,
  FavoritesRoute: FavoritesRoute,
  FeaturedRoute: FeaturedRoute,
  GoRoute: GoRoute,
  HomeBusinessesRoute: HomeBusinessesRoute,
  McpRoute: McpRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantsRoute: RestaurantsRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupermarketsRoute: SupermarketsRoute,
  TermsRoute: TermsRoute,
  WaitlistRoute: WaitlistRoute,
  BusinessIdRoute: BusinessIdRoute,
  CSlugRoute: CSlugRoute,
  SServiceRoute: SServiceRoute,
  ApiPublicCoverRoute: ApiPublicCoverRouteWithChildren,
  ApiPublicEventRoute: ApiPublicEventRoute,
  ApiPublicSheetSyncRoute: ApiPublicSheetSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
